class AppRoutes {
  static const String language = '/language';
  static const String scan = '/scan';
  static const String chat = '/chat';
  static const String processing = '/processing';
  static const String result = '/result';
}

/// Lightweight translation map for 4 supported languages.
/// Keys are string IDs, values are translated strings.
const Map<String, Map<String, String>> appStrings = {
  'en': {
    'app_name': 'VitalAccess',
    'app_tagline': 'Health triage in your pocket',
    'disclaimer_short': 'This app provides health triage, not medical diagnosis.',
    'disclaimer_full':
        'This is not a medical diagnosis. Please consult a healthcare professional.',
    'select_language': 'Select your language',
    'scan_instruction': 'Hold your phone at arm\'s length and look at the camera',
    'scan_title': 'Vitals Scan',
    'face_guide_no_face': 'Position your face in the oval',
    'face_guide_motion': 'Try to stay still',
    'face_guide_brightness': 'Find better lighting',
    'face_guide_starting': 'Hold still, we\'re getting started',
    'face_guide_good': 'Looking good, keep still',
    'face_guide_almost': 'Almost done...',
    'face_guide_complete': 'Complete!',
    'signal_quality': 'Signal quality',
    'chat_hint': 'Type your answer...',
    'chat_skip': 'Skip',
    'processing_vitals': 'Analyzing your vitals...',
    'processing_symptoms': 'Assessing symptoms...',
    'processing_urgency': 'Determining urgency level...',
    'processing_summary': 'Preparing your summary...',
    'share_summary': 'Share Summary',
    'save_pdf': 'Save as PDF',
    'start_over': 'Start Over',
    'heart_rate': 'Heart Rate',
    'hrv': 'HRV',
    'resp_rate': 'Resp. Rate',
    'confidence': 'Confidence',
    'bpm': 'bpm',
    'ms': 'ms',
    'per_min': '/min',
    'retry': 'Retry',
    'demo_vitals': 'Use Demo Vitals',
    'server_not_found':
        'Vitals server not detected. Start the CV Pipeline server or continue with demo vitals.',
    'vitals_summary': 'VitalAccess Health Summary',
    'symptoms_reported': 'Symptoms Reported',
    'triage_result': 'Triage Result',
    'watch_for': 'Seek immediate care if...',
    'session_id': 'Session ID',
  },
  'fr': {
    'app_name': 'VitalAccess',
    'app_tagline': 'Le triage de santé dans votre poche',
    'disclaimer_short': 'Cette application fournit un triage de santé, pas un diagnostic médical.',
    'disclaimer_full':
        'Ceci n\'est pas un diagnostic médical. Veuillez consulter un professionnel de santé.',
    'select_language': 'Sélectionnez votre langue',
    'scan_instruction': 'Tenez votre téléphone à bout de bras et regardez la caméra',
    'scan_title': 'Scan des Signes Vitaux',
    'face_guide_no_face': 'Positionnez votre visage dans l\'ovale',
    'face_guide_motion': 'Essayez de rester immobile',
    'face_guide_brightness': 'Trouvez un meilleur éclairage',
    'face_guide_starting': 'Restez immobile, nous démarrons',
    'face_guide_good': 'Bien, restez immobile',
    'face_guide_almost': 'Presque terminé...',
    'face_guide_complete': 'Terminé!',
    'signal_quality': 'Qualité du signal',
    'chat_hint': 'Tapez votre réponse...',
    'chat_skip': 'Passer',
    'processing_vitals': 'Analyse de vos signes vitaux...',
    'processing_symptoms': 'Évaluation des symptômes...',
    'processing_urgency': 'Détermination du niveau d\'urgence...',
    'processing_summary': 'Préparation de votre résumé...',
    'share_summary': 'Partager le Résumé',
    'save_pdf': 'Enregistrer en PDF',
    'start_over': 'Recommencer',
    'heart_rate': 'Fréquence Cardiaque',
    'hrv': 'VRC',
    'resp_rate': 'Fréq. Resp.',
    'confidence': 'Confiance',
    'bpm': 'bpm',
    'ms': 'ms',
    'per_min': '/min',
    'retry': 'Réessayer',
    'demo_vitals': 'Utiliser des Données Démo',
    'server_not_found':
        'Serveur de signes vitaux non détecté. Démarrez le serveur CV Pipeline ou continuez avec des données démo.',
    'vitals_summary': 'Résumé de Santé VitalAccess',
    'symptoms_reported': 'Symptômes Signalés',
    'triage_result': 'Résultat du Triage',
    'watch_for': 'Cherchez des soins immédiats si...',
    'session_id': 'ID de Session',
  },
  'es': {
    'app_name': 'VitalAccess',
    'app_tagline': 'Triaje de salud en tu bolsillo',
    'disclaimer_short': 'Esta aplicación proporciona triaje de salud, no diagnóstico médico.',
    'disclaimer_full':
        'Esto no es un diagnóstico médico. Por favor consulte a un profesional de salud.',
    'select_language': 'Selecciona tu idioma',
    'scan_instruction': 'Sostén el teléfono a la distancia de un brazo y mira a la cámara',
    'scan_title': 'Escaneo de Signos Vitales',
    'face_guide_no_face': 'Posiciona tu cara en el óvalo',
    'face_guide_motion': 'Intenta quedarte quieto',
    'face_guide_brightness': 'Busca mejor iluminación',
    'face_guide_starting': 'Quédate quieto, estamos empezando',
    'face_guide_good': 'Bien, sigue quieto',
    'face_guide_almost': 'Casi listo...',
    'face_guide_complete': '¡Completo!',
    'signal_quality': 'Calidad de señal',
    'chat_hint': 'Escribe tu respuesta...',
    'chat_skip': 'Omitir',
    'processing_vitals': 'Analizando tus signos vitales...',
    'processing_symptoms': 'Evaluando síntomas...',
    'processing_urgency': 'Determinando nivel de urgencia...',
    'processing_summary': 'Preparando tu resumen...',
    'share_summary': 'Compartir Resumen',
    'save_pdf': 'Guardar como PDF',
    'start_over': 'Empezar de Nuevo',
    'heart_rate': 'Frecuencia Cardíaca',
    'hrv': 'VFC',
    'resp_rate': 'Frec. Resp.',
    'confidence': 'Confianza',
    'bpm': 'bpm',
    'ms': 'ms',
    'per_min': '/min',
    'retry': 'Reintentar',
    'demo_vitals': 'Usar Datos de Demo',
    'server_not_found':
        'Servidor de signos vitales no detectado. Inicia el servidor CV Pipeline o continúa con datos demo.',
    'vitals_summary': 'Resumen de Salud VitalAccess',
    'symptoms_reported': 'Síntomas Reportados',
    'triage_result': 'Resultado del Triaje',
    'watch_for': 'Busca atención inmediata si...',
    'session_id': 'ID de Sesión',
  },
  'ar': {
    'app_name': 'VitalAccess',
    'app_tagline': 'الفرز الصحي في جيبك',
    'disclaimer_short': 'يوفر هذا التطبيق الفرز الصحي، وليس التشخيص الطبي.',
    'disclaimer_full':
        'هذا ليس تشخيصًا طبيًا. يرجى استشارة أخصائي رعاية صحية.',
    'select_language': 'اختر لغتك',
    'scan_instruction': 'امسك هاتفك على مسافة ذراع وانظر إلى الكاميرا',
    'scan_title': 'مسح العلامات الحيوية',
    'face_guide_no_face': 'ضع وجهك في البيضاوي',
    'face_guide_motion': 'حاول البقاء ثابتًا',
    'face_guide_brightness': 'ابحث عن إضاءة أفضل',
    'face_guide_starting': 'ابق ثابتًا، نحن نبدأ',
    'face_guide_good': 'ممتاز، ابق ثابتًا',
    'face_guide_almost': 'اكتمل تقريبًا...',
    'face_guide_complete': 'اكتمل!',
    'signal_quality': 'جودة الإشارة',
    'chat_hint': 'اكتب إجابتك...',
    'chat_skip': 'تخطي',
    'processing_vitals': 'تحليل علاماتك الحيوية...',
    'processing_symptoms': 'تقييم الأعراض...',
    'processing_urgency': 'تحديد مستوى الإلحاح...',
    'processing_summary': 'إعداد ملخصك...',
    'share_summary': 'مشاركة الملخص',
    'save_pdf': 'حفظ كـ PDF',
    'start_over': 'ابدأ من جديد',
    'heart_rate': 'معدل ضربات القلب',
    'hrv': 'تقلب معدل ضربات القلب',
    'resp_rate': 'معدل التنفس',
    'confidence': 'الثقة',
    'bpm': 'نبضة/دقيقة',
    'ms': 'مللي ثانية',
    'per_min': '/دقيقة',
    'retry': 'إعادة المحاولة',
    'demo_vitals': 'استخدام بيانات تجريبية',
    'server_not_found':
        'لم يتم اكتشاف خادم العلامات الحيوية. قم بتشغيل خادم CV Pipeline أو استمر مع بيانات تجريبية.',
    'vitals_summary': 'ملخص صحة VitalAccess',
    'symptoms_reported': 'الأعراض المُبلَّغ عنها',
    'triage_result': 'نتيجة الفرز',
    'watch_for': 'اطلب رعاية فورية إذا...',
    'session_id': 'معرف الجلسة',
  },
};

/// Get a translated string by key for the given language code.
/// Falls back to English if the key or language is not found.
String t(String languageCode, String key) {
  return appStrings[languageCode]?[key] ?? appStrings['en']?[key] ?? key;
}
